[package]
name = "eazip"
version = "0.2.0"
edition = "2024"
rust-version = "1.87"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "An simple yet flexible zip library"

repository = "https://github.com/a1phyr/eazip"
documentation = "https://docs.rs/eazip"

categories = ["compression"]
keywords = ["zip", "archive"]

[features]
default = ["deflate", "zstd", "std"]

# Mandatory feature for forward-compatibility.
std = []
# Enable deflate compression and decompression.
deflate = ["dep:flate2"]
# Enable zstd compression and decompression.
zstd = ["dep:zstd"]

# Enable parallel ZIP file extraction.
parallel = ["dep:rayon", "dep:sync_file"]


[dependencies]
crc32fast = "1.4.2"
flate2 = { version = "1.1.0", optional = true }
memchr = "2.7.4"
zstd = { version = "0.13.3", optional = true }

rayon = { version = "1.10", optional = true }
sync_file = { version = "0.3", optional = true }
