[package]
name = "zip-ng"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
license = "MIT OR Apache-2.0"
readme = "README.md"


[features]
default = ["deflate", "zstd", "std"]

std = []
deflate = ["dep:flate2"]
zstd = ["dep:zstd"]

parallel = ["dep:rayon", "dep:sync_file"]


[dependencies]
crc32fast = "1.4.2"
flate2 = { version = "1.1.0", optional = true }
memchr = "2.7.4"
zstd = { version = "0.13.3", optional = true }

rayon = { version = "1.10", optional = true }
sync_file = { version = "0.3", optional = true }
